import type { Metadata, Viewport } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

// Imported from their own modules rather than the barrels: a barrel makes
// the root layout depend on every component in it, which is how the Firebase
// SDK ends up in the bundle for a static marketing page.
import { ThemeProvider } from '@/components/layout/theme-provider';
import { JsonLd } from '@/components/marketing/json-ld';
import { Toaster } from '@/components/ui/toast';
import { TooltipProvider } from '@/components/ui/tooltip';
import { absoluteUrl, organizationSchema, SITE_KEYWORDS, SITE_ORIGIN } from '@/lib/site';
import { DEFAULT_RESOLVED_THEME, THEME_BOOTSTRAP_SCRIPT } from '@/lib/theme';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  // Every relative URL in any page's metadata — canonicals, Open Graph images,
  // alternates — is resolved against this. Without it Next emits relative
  // `og:url` values, which crawlers and link unfurlers cannot follow, so the
  // one page whose preview matters most is the one that renders bare.
  metadataBase: new URL(SITE_ORIGIN),
  title: {
    default: 'xecret — secret management for developers',
    template: '%s · xecret',
  },
  description:
    'Open-source, developer-first secret management. Encrypted per environment, audited on every read, and wired into your app with one command.',
  applicationName: 'xecret',
  keywords: [...SITE_KEYWORDS],
  authors: [{ name: 'Playxoft', url: 'https://playxoft.com' }],
  creator: 'Playxoft',
  publisher: 'Playxoft',
  // The public pages are indexable. Pages that must not be — anything reached
  // through a single-use link, such as password reset — override this in their
  // own `metadata`, and every dashboard route sits behind a session so a
  // crawler collects nothing but redirects.
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      // Let Google use the full snippet, a large image preview and any video
      // it finds. The defaults are conservative, and a truncated snippet on a
      // documentation result is a click that goes to whoever wrote a longer one.
      'max-snippet': -1,
      'max-image-preview': 'large',
      'max-video-preview': -1,
    },
  },
  alternates: { canonical: '/' },
  other: { 'darkreader-lock': 'true' },
  openGraph: {
    type: 'website',
    url: absoluteUrl('/'),
    siteName: 'xecret',
    locale: 'en_GB',
    title: 'xecret — secret management for developers',
    description: 'Open-source, developer-first secret management. Powered by Playxoft.',
    // One card for the whole site, generated by `npm run og` — see
    // scripts/generate-og.ts for why it is a committed PNG rather than a
    // runtime `ImageResponse`. Pages inherit it and override only their
    // `title` and `description`, which is the part an unfurler shows anyway.
    images: [
      {
        url: '/og.png',
        width: 1200,
        height: 630,
        alt: 'xecret — secret management that gets out of your way. Encrypted per environment, audited on every read, open source.',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'xecret — secret management for developers',
    description: 'Open-source, developer-first secret management. Powered by Playxoft.',
    images: ['/og.png'],
  },
  // No `icons` key: `app/icon.svg`, `app/favicon.ico` and `app/apple-icon.png`
  // are already picked up by the file convention, and declaring them here as
  // well emits a second set of <link> tags for the same three files.
};

export const viewport: Viewport = {
  // Matches --canvas in each theme, so the browser chrome on mobile does not
  // sit as a bright band above a dark page. These two values are the literal
  // --canvas tokens from globals.css; a `<meta>` tag cannot read a custom
  // property, so they are the one place in the application where a surface
  // colour is written twice. Change one and change the other.
  themeColor: [
    { media: '(prefers-color-scheme: dark)', color: '#0a0a0a' },
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
  ],
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      // Dark is the server-rendered default; the bootstrap script below
      // rewrites this before first paint from the stored preference. React
      // then hydrates against a value it did not render, which is exactly what
      // `suppressHydrationWarning` is for.
      data-theme={DEFAULT_RESOLVED_THEME}
      data-sidebar="expanded"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* Must be inline and render-blocking — see THEME_BOOTSTRAP_SCRIPT for
            why. Its content is a module constant, not user input. */}
        <script dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP_SCRIPT }} />

        {/* The public pages animate their sections in on scroll, which means
            those sections rest at `opacity: 0` until an IntersectionObserver
            says otherwise. With scripting off, nothing ever says otherwise —
            so the same stylesheet's hidden state is cancelled here. A reader
            without JavaScript loses the animation and keeps the article. */}
        <noscript>
          <style>
            {'.x-reveal,.x-reveal-group>*{opacity:1!important;transform:none!important}'}
          </style>
        </noscript>

        {/* `Organization` and `WebSite`, once for the whole site. Every page's
            own graph references these by `@id` instead of restating them. */}
        <JsonLd data={organizationSchema()} />
      </head>
      <body className="flex min-h-full flex-col">
        <ThemeProvider>
          <TooltipProvider>
            <Toaster>{children}</Toaster>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
