import { describe, expect, it, vi } from 'vitest';
import { getTableName } from 'drizzle-orm';
import { DEVICE_PIN_MAX_ATTEMPTS, nextPinFailure } from '@xecret/core/auth';
import { uuidv7 } from '@xecret/core/ids';
import { createDatabase } from '../client';
import { attemptPinUnlock, pinDeviceQuery, pinDevicesQuery } from './vault-pin';

/**
 * The two collaborators the reset reaches that have nothing to do with PINs.
 *
 * Replaced so the rotation tests below exercise one question — which tables a
 * rotation writes to — without also standing up a fake for the grant sweep and
 * the session lock, whose own behaviour is not what is being asserted.
 */
vi.mock('./env-keys', () => ({ deleteGrantsForUser: vi.fn(() => Promise.resolve(0)) }));
vi.mock('./sessions', () => ({ lockSessions: vi.fn(() => Promise.resolve(0)) }));

const { changePassphrase, completeRecovery, resetVault } = await import('./vault');

/**
 * Shape tests, like the rest of this directory: there is no PostgreSQL behind
 * this file, so what they pin is the SQL the pin repository generates and the
 * policy the counter follows.
 *
 * What they deliberately do not claim: that the attempt transaction really
 * serialises two concurrent guesses, that `FOR UPDATE` really blocks the second
 * reader, or that the upsert really replaces rather than duplicating. Those are
 * properties of PostgreSQL and belong to the integration pass — the standing
 * caveat `identity.test.ts` records. What this file makes impossible is a
 * refactor that quietly drops the row lock, drops half the primary key, or puts
 * a pepper into a listing.
 */

/** Never queried. postgres.js connects lazily, so `.toSQL()` opens no socket. */
const db = createDatabase({ connectionString: 'postgres://xecret@localhost:5432/xecret' });

const USER_ID = uuidv7();
const DEVICE_ID = uuidv7();

describe('reading the row one PIN attempt is judged against', () => {
  const query = () => pinDeviceQuery(db, USER_ID, DEVICE_ID).toSQL();

  it('names both halves of the primary key', () => {
    // A device id is generated by the client, so it is not a global name. A
    // predicate missing `user_id` would be one account reaching another's row.
    const { sql, params } = query();

    expect(sql).toContain('"vault_pin_peppers"."user_id" = $1');
    expect(sql).toContain('"vault_pin_peppers"."device_id" = $2');
    // The trailing parameter is the `limit`.
    expect(params.slice(0, 2)).toEqual([USER_ID, DEVICE_ID]);
  });

  it('locks the row it read', () => {
    // The load-bearing clause of the whole feature. Without it two concurrent
    // attempts both read `attempts = 4`, and a scripted attacker gets as many
    // guesses per round trip as they care to open connections — which is the one
    // thing a six-digit credential cannot survive.
    expect(query().sql).toMatch(/for update/i);
  });

  it('reads exactly the three columns the decision needs', () => {
    const { sql } = query();

    expect(sql).toContain('"pepper"');
    expect(sql).toContain('"verifier_hash"');
    expect(sql).toContain('"attempts"');
    expect(sql).toContain('limit');
  });
});

describe('listing the browsers an account has enrolled', () => {
  const query = () => pinDevicesQuery(db, USER_ID).toSQL();

  it('filters on the account', () => {
    const { sql, params } = query();

    expect(sql).toContain('"vault_pin_peppers"."user_id" = $1');
    expect(params).toContain(USER_ID);
  });

  it('never selects the pepper or the verifier digest', () => {
    // The directory's second rule, and it matters more here than anywhere: the
    // pepper is half of a wrap key, and a column that is never selected cannot
    // be logged by accident.
    const { sql } = query();

    expect(sql).not.toContain('pepper"');
    expect(sql).not.toContain('verifier_hash');
  });

  it('orders newest first, which is the order the settings list reads in', () => {
    expect(query().sql).toMatch(/order by .*"created_at" desc/i);
  });
});

describe('what the repository does with a failed attempt', () => {
  it('spends one try per failure and burns on the fifth', () => {
    // Restated here as well as in `packages/core` because this is the module
    // that acts on it: the fourth failure updates a row, the fifth deletes one,
    // and the two are not interchangeable.
    const outcomes = Array.from({ length: DEVICE_PIN_MAX_ATTEMPTS }, (_, attempts) =>
      nextPinFailure(attempts),
    );

    expect(outcomes.filter((outcome) => outcome.burned)).toHaveLength(1);
    expect(outcomes.at(-1)?.burned).toBe(true);
    expect(outcomes.map((outcome) => outcome.attemptsRemaining)).toEqual([4, 3, 2, 1, 0]);
  });

  it('never stores a counter the table would refuse', () => {
    // `vault_pin_peppers_attempts_check` bounds the column at
    // [0, DEVICE_PIN_MAX_ATTEMPTS]. Anything past it burns instead of writing.
    for (let attempts = 0; attempts < 20; attempts += 1) {
      const outcome = nextPinFailure(attempts);
      expect(outcome.attempts, String(attempts)).toBeLessThanOrEqual(DEVICE_PIN_MAX_ATTEMPTS);
      expect(outcome.attempts, String(attempts)).toBeGreaterThanOrEqual(0);
    }
  });
});

/**
 * A stand-in that answers one row and records what was written to it.
 *
 * Narrower than `recordingExecutor` below on purpose: what these tests need to
 * see is the *payload* of the update, not which table it addressed.
 */
function pepperRowExecutor(row: {
  pepper: Uint8Array;
  verifierHash: Uint8Array;
  attempts: number;
}) {
  const writes: Record<string, unknown>[] = [];
  const deletes: number[] = [];

  const selectChain = {
    from: () => selectChain,
    where: () => selectChain,
    limit: () => selectChain,
    for: () => selectChain,
    then: (resolve: (value: unknown[]) => unknown) => Promise.resolve([row]).then(resolve),
  };

  const exec = {
    transaction: (run: (tx: unknown) => Promise<unknown>) => run(exec),
    select: () => selectChain,
    update: () => ({
      set: (payload: Record<string, unknown>) => {
        writes.push(payload);
        return { where: () => Promise.resolve({ count: 1 }) };
      },
    }),
    delete: () => ({
      where: () => {
        deletes.push(1);
        return Promise.resolve({ count: 1 });
      },
    }),
  };

  return { exec, writes, deletes };
}

describe('what a successful attempt does to the pepper it just released', () => {
  const stored = new Uint8Array(32).fill(1);
  const replacement = new Uint8Array(32).fill(2);

  it('hands back the old pepper and stores the new one in the same statement', async () => {
    // A pepper is released to the client on every unlock, so one that never
    // changes only has to be intercepted once — and the pair it forms with a
    // copy of that browser's `localStorage` needs no server afterwards, which is
    // what makes revocation unable to take it back. Rotating narrows the
    // exposure of any single pepper to one unlock.
    const { exec, writes } = pepperRowExecutor({
      pepper: stored,
      verifierHash: new Uint8Array(32).fill(9),
      attempts: 3,
    });

    const outcome = await attemptPinUnlock(exec as never, {
      userId: USER_ID,
      deviceId: DEVICE_ID,
      matches: () => Promise.resolve(true),
      nextPepper: replacement,
    });

    // The wrap on that browser was built under the *old* one, so that is what
    // has to come back — it is the last time this value opens anything.
    expect(outcome).toEqual({ status: 'ok', pepper: stored });

    // One write, carrying the rotation alongside the reset. A second statement
    // would leave a window in which the released pepper and the stored one
    // disagree.
    expect(writes).toHaveLength(1);
    expect(writes[0]).toMatchObject({ attempts: 0, pepper: replacement });
    expect(writes[0]?.['lastUsedAt']).toBeInstanceOf(Date);
  });

  it('leaves the stored pepper alone on a miss', async () => {
    // A wrong PIN spends an attempt and nothing else. Rotating here would
    // destroy a working enrolment on a typo.
    const { exec, writes } = pepperRowExecutor({
      pepper: stored,
      verifierHash: new Uint8Array(32).fill(9),
      attempts: 1,
    });

    const outcome = await attemptPinUnlock(exec as never, {
      userId: USER_ID,
      deviceId: DEVICE_ID,
      matches: () => Promise.resolve(false),
      nextPepper: replacement,
    });

    expect(outcome).toEqual({ status: 'wrong', attemptsRemaining: 3 });
    expect(writes).toHaveLength(1);
    expect(writes[0]).not.toHaveProperty('pepper');
  });

  it('deletes rather than rotates on the fifth failure', async () => {
    const { exec, writes, deletes } = pepperRowExecutor({
      pepper: stored,
      verifierHash: new Uint8Array(32).fill(9),
      attempts: DEVICE_PIN_MAX_ATTEMPTS - 1,
    });

    const outcome = await attemptPinUnlock(exec as never, {
      userId: USER_ID,
      deviceId: DEVICE_ID,
      matches: () => Promise.resolve(false),
      nextPepper: replacement,
    });

    expect(outcome).toEqual({ status: 'burned' });
    expect(deletes).toHaveLength(1);
    expect(writes).toHaveLength(0);
  });
});

/**
 * A recording stand-in for a transaction.
 *
 * ── What this is for, and the limit of what it can say ──
 * The three acts that rotate a vault — a passphrase change, a recovery and a
 * reset — each destroy every device PIN, and they do it *inside their own
 * transaction* rather than in the service above them, so that a rotation cannot
 * half-happen and leave peppers alive for wraps that no longer open anything.
 * That placement is invisible from outside: the service sees one call, and a
 * shape test on a query builder cannot reach a statement issued three lines into
 * a transaction callback.
 *
 * So this records which table each statement addressed. It proves the delete is
 * *issued, inside the transaction*, and nothing more — not that PostgreSQL rolls
 * it back with the rest, which is the integration pass's job and is the reason
 * the placement was chosen rather than a claim this file makes.
 */
function recordingExecutor() {
  const statements: { verb: string; table: string }[] = [];

  function chain(rows: readonly unknown[]) {
    const self: Record<string, unknown> = {};
    for (const method of [
      'set',
      'values',
      'where',
      'returning',
      'onConflictDoUpdate',
      'from',
      'limit',
      'orderBy',
      'for',
    ]) {
      self[method] = () => self;
    }
    self['then'] = (resolve: (value: readonly unknown[]) => unknown) =>
      Promise.resolve(rows).then(resolve);
    return self;
  }

  function record(verb: string) {
    return (table: Parameters<typeof getTableName>[0]) => {
      statements.push({ verb, table: getTableName(table) });
      // One row, so every `returning()` the repository checks for emptiness
      // reads as "the write landed" — the path these tests are about.
      return chain([{ id: uuidv7(), userId: USER_ID }]);
    };
  }

  const exec = {
    transaction: (run: (tx: unknown) => Promise<unknown>) => run(exec),
    insert: record('insert'),
    update: record('update'),
    delete: record('delete'),
    select: () => chain([{ id: uuidv7() }]),
  };

  return { exec, statements };
}

const KDF_PARAMS = { alg: 'argon2id', v: 19, m: 65_536, t: 3, p: 1, len: 32 } as const;

function rotationParams() {
  return {
    userId: USER_ID,
    kdfSalt: new Uint8Array(16),
    kdfParams: KDF_PARAMS,
    unlockVerifierHash: new Uint8Array(32),
    passphraseWrap: new Uint8Array([1, 2, 3]),
  };
}

describe('what a vault rotation does to every device PIN', () => {
  it('destroys them on a passphrase change', async () => {
    // Policy rather than correctness here — a passphrase change re-wraps the
    // User Key rather than replacing it, so the PIN wraps would still open. D3
    // revokes them anyway: somebody changing their passphrase is re-deciding who
    // may reach this account, and a shortcut enrolled on a browser they no
    // longer hold is not something that decision should silently keep alive.
    const { exec, statements } = recordingExecutor();

    await changePassphrase(exec as never, rotationParams());

    expect(statements).toContainEqual({ verb: 'delete', table: 'vault_pin_peppers' });
  });

  it('destroys them on a recovery', async () => {
    const { exec, statements } = recordingExecutor();

    await completeRecovery(exec as never, {
      ...rotationParams(),
      wrapId: uuidv7(),
      recoveryWraps: [{ lookupHash: new Uint8Array(32), wrap: new Uint8Array([1]) }],
    });

    expect(statements).toContainEqual({ verb: 'delete', table: 'vault_pin_peppers' });
  });

  it('destroys them on a vault reset, where the User Key itself is replaced', async () => {
    // The one of the three where this is not a policy choice: a reset abandons
    // the User Key, so every PIN wrap becomes a ciphertext of a key that no
    // longer exists. The server cannot delete those wraps — they are in
    // browsers — so removing the pepper is the only way to make them
    // unopenable, and leaving one would keep that browser offering an unlock
    // that can only fail.
    const { exec, statements } = recordingExecutor();

    await resetVault(exec as never, USER_ID);

    expect(statements).toContainEqual({ verb: 'delete', table: 'vault_pin_peppers' });
  });
});
