import { importAesKey, KEY_LENGTH } from './aead';
import { fromBase64Url } from './encoding';
import { UnknownKeyVersionError } from './types';
import type { KeyProvider } from './types';
import type { Bytes } from './types';

/**
 * Sources for the Root Key Encryption Key.
 *
 * The key originates in Phase.dev, is pushed to Cloudflare Secrets Store at
 * deploy time, and is read from a binding at runtime. The Worker never contacts
 * Phase.dev while serving a request — see ADR 0002.
 */

/**
 * Wire format for `XECRET_ROOT_KEYS`: a JSON object mapping key version to
 * base64url-encoded 256-bit key material.
 *
 *     {"1":"<43 base64url chars>","2":"<43 base64url chars>"}
 *
 * A map rather than a single value because rotation needs both keys readable at
 * once: rows wrapped under version 1 stay readable until every one has been
 * re-wrapped under version 2. Once the re-wrap completes, version 1 is removed
 * from the map — and only then may its escrow shares be destroyed.
 *
 * Generated by `scripts/keygen.mjs`; never assembled by hand.
 */
export interface RootKeyMaterial {
  currentVersion: number;
  keys: ReadonlyMap<number, Bytes>;
}

export class InvalidRootKeyMaterialError extends Error {
  constructor(reason: string) {
    // Reasons are structural ("not an object", "wrong length") and never echo
    // key material, so this is safe to log.
    super(`Invalid root key material: ${reason}`);
    this.name = 'InvalidRootKeyMaterialError';
  }
}

/**
 * Parses and validates the `XECRET_ROOT_KEYS` JSON blob.
 *
 * Validation is strict and happens once at startup rather than lazily on first
 * decryption. A misconfigured key should fail the deploy loudly, not surface
 * hours later as an unexplained decryption failure on a customer's request.
 */
export function parseRootKeyMaterial(json: string, currentVersion: number): RootKeyMaterial {
  if (!Number.isInteger(currentVersion) || currentVersion < 1) {
    throw new InvalidRootKeyMaterialError('currentVersion must be a positive integer');
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(json);
  } catch {
    throw new InvalidRootKeyMaterialError('not valid JSON');
  }

  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new InvalidRootKeyMaterialError('expected a JSON object mapping version to key');
  }

  const keys = new Map<number, Bytes>();

  for (const [versionText, encoded] of Object.entries(parsed as Record<string, unknown>)) {
    // `Number()` on '1.5' or '0x2' would silently produce a plausible version.
    if (!/^[1-9][0-9]*$/.test(versionText)) {
      throw new InvalidRootKeyMaterialError(
        `key version "${versionText}" is not a positive integer`,
      );
    }
    if (typeof encoded !== 'string') {
      throw new InvalidRootKeyMaterialError(`key for version ${versionText} is not a string`);
    }

    let bytes: Bytes;
    try {
      bytes = fromBase64Url(encoded);
    } catch {
      throw new InvalidRootKeyMaterialError(
        `key for version ${versionText} is not valid base64url`,
      );
    }

    if (bytes.length !== KEY_LENGTH) {
      throw new InvalidRootKeyMaterialError(
        `key for version ${versionText} must be ${KEY_LENGTH} bytes, got ${bytes.length}`,
      );
    }

    keys.set(Number.parseInt(versionText, 10), bytes);
  }

  if (keys.size === 0) {
    throw new InvalidRootKeyMaterialError('no keys provided');
  }

  if (!keys.has(currentVersion)) {
    throw new InvalidRootKeyMaterialError(
      `currentVersion ${currentVersion} is not present in the key map`,
    );
  }

  return { currentVersion, keys };
}

/**
 * Holds root key material for the lifetime of an isolate.
 *
 * `CryptoKey` objects are imported lazily and cached: importing is cheap, but
 * doing it per request would be needless work on the hottest path in the system.
 */
export class InMemoryKeyProvider implements KeyProvider {
  readonly #material: RootKeyMaterial;
  readonly #imported = new Map<number, Promise<CryptoKey>>();

  constructor(material: RootKeyMaterial) {
    this.#material = material;
  }

  currentVersion(): number {
    return this.#material.currentVersion;
  }

  getRootKey(version: number): Promise<CryptoKey> {
    const cached = this.#imported.get(version);
    if (cached) return cached;

    const bytes = this.#material.keys.get(version);
    if (!bytes) {
      // Reached when a stored row references a root version that has been
      // retired from the key map — i.e. a rotation was completed before every
      // row was re-wrapped. Loud and specific, because it is an operator error.
      return Promise.reject(new UnknownKeyVersionError(version));
    }

    // Cache the promise, not the resolved key, so concurrent callers during a
    // cold start share one import instead of racing.
    const imported = importAesKey(bytes, ['encrypt', 'decrypt']);
    this.#imported.set(version, imported);
    return imported;
  }

  /** Versions this provider can serve, ascending. For rotation tooling. */
  availableVersions(): readonly number[] {
    return [...this.#material.keys.keys()].sort((a, b) => a - b);
  }
}

/** The subset of the Cloudflare Secrets Store binding that xecret uses. */
export interface SecretsStoreBinding {
  get(): Promise<string>;
}

/**
 * Builds a provider from a Cloudflare Secrets Store binding.
 *
 * Call once per isolate at startup and reuse the result. Calling it per request
 * would add a binding read to the hot path for no benefit — the value cannot
 * change within an isolate's lifetime.
 */
export async function keyProviderFromSecretsStore(
  binding: SecretsStoreBinding,
  currentVersion: number,
): Promise<InMemoryKeyProvider> {
  return new InMemoryKeyProvider(parseRootKeyMaterial(await binding.get(), currentVersion));
}

/**
 * Builds a provider from environment variables.
 *
 * Used for local development, tests, and self-hosted deployments without
 * Cloudflare Secrets Store.
 */
export function keyProviderFromEnv(env: {
  XECRET_ROOT_KEYS?: string | undefined;
  XECRET_ROOT_KEY_VERSION?: string | undefined;
}): InMemoryKeyProvider {
  if (!env.XECRET_ROOT_KEYS) {
    throw new InvalidRootKeyMaterialError(
      'XECRET_ROOT_KEYS is not set. Secrets come from Phase.dev — try: phase run -- <command>',
    );
  }

  const version = Number(env.XECRET_ROOT_KEY_VERSION ?? '1');
  return new InMemoryKeyProvider(parseRootKeyMaterial(env.XECRET_ROOT_KEYS, version));
}
