import { cn } from '@/lib/cn';

/**
 * The xecret mark.
 *
 * ── One drawing, two places ──
 * This is the same geometry and the same gradient as the favicon, which is
 * generated by `scripts/generate-icons.ts`. Deliberately identical: a mark that
 * differs between the browser tab and the page it labels is not a mark, it is
 * two logos that happen to share a product. The numbers below — a 32-unit box,
 * an 8-unit corner radius, arms from 8.5 to 23.5, a 3.2 stroke — were settled
 * at 16px in that script, because that is the size a favicon has to survive.
 * Change one and change the other, then run `npm run icons`.
 *
 * ── Fixed colours rather than theme tokens ──
 * The chip used to be `var(--accent)` so it flipped with the theme. It no
 * longer does, and that is the point of a brand mark: it is the one element on
 * the page that should look the same wherever it appears, including in a tab
 * strip whose colour the application does not control. The gradient runs from
 * the accent's own cyan into a deep blue, so it still belongs to the palette
 * without being subject to it.
 */
export function LogoMark({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 32 32"
      className={cn('size-6', className)}
      fill="none"
      aria-hidden="true"
      focusable="false"
    >
      <defs>
        {/* A fixed id rather than `useId`: this file is imported by Server
            Components — the marketing page and the auth layout — where hooks
            cannot run, and making it a client component to generate a string
            would pull the mark into every consumer's bundle. Two instances on
            one page therefore share an id; both definitions are identical, so
            `url(#…)` resolving to the first renders correctly either way. */}
        <linearGradient
          id="xecret-mark-gradient"
          x1="0"
          y1="0"
          x2="32"
          y2="32"
          gradientUnits="userSpaceOnUse"
        >
          <stop offset="0" stopColor="#3ad4ec" />
          <stop offset="0.55" stopColor="#2380e2" />
          <stop offset="1" stopColor="#2a3fd0" />
        </linearGradient>
      </defs>
      <rect width="32" height="32" rx="8" fill="url(#xecret-mark-gradient)" />
      <path
        d="M8.5 8.5L23.5 23.5M23.5 8.5L8.5 23.5"
        stroke="#ffffff"
        strokeWidth="3.2"
        strokeLinecap="round"
      />
    </svg>
  );
}

export function Wordmark({ className }: { className?: string }) {
  return (
    <span className={cn('inline-flex items-center gap-2', className)}>
      <LogoMark className="size-6 shrink-0" />
      <span className="text-fg text-[0.9375rem] font-semibold tracking-tight">xecret</span>
    </span>
  );
}

/**
 * The attribution mark. Deliberately quiet: it belongs in a footer or the base
 * of a sign-in card, not competing with the product name.
 *
 * A link to the company site, in a new tab — the reader is mid-task in xecret
 * (often mid-sign-in), and attribution must not navigate them out of it.
 * `rel="noopener noreferrer"` because every `target="_blank"` gets it: the
 * opened page must not hold a handle back to a window with a session in it.
 */
export function PlayxoftMark({ className }: { className?: string }) {
  return (
    <a
      href="https://playxoft.com"
      target="_blank"
      rel="noopener noreferrer"
      className={cn(
        'text-fg-subtle inline-flex items-center gap-1.5 rounded-sm text-sm transition-colors',
        'hover:text-fg-muted',
        className,
      )}
    >
      <span
        aria-hidden="true"
        className="bg-fg-subtle/40 inline-block h-3 w-px shrink-0 rotate-12 rounded-full"
      />
      Powered by <span className="text-fg-muted font-medium">Playxoft</span>
    </a>
  );
}
